version: "3.9"
services:
  app:
#    build:
#      context: ./
#      dockerfile: Dockerfile
    image: dipppp84/rest_service:v1
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./src:/node/app/src
    networks:
      - mynet
    restart: always

    ports:
      - ${PORT}:${PORT}

  postgres:
#    build:
#      context: db
#      dockerfile: Dockerfile
    image: dipppp84/rest_db:v1
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynet
    restart: always
    ports:
      - ${PORT_DB}:${PORT_DB}

networks:
  mynet:
    driver: bridge
volumes:
  pgdata: